### ISSUE TITLE
error flask.cli.NoAppException

### ISSUE THREAD

**Issue by jayo2005** [christopherchoe/lastmanstanding#1]
When I run I get

```
flask.cli.NoAppException
flask.cli.NoAppException: While importing "root.app", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/root/app.py", line 2, in <module>
    from templates import app
ModuleNotFoundError: No module named 'templates'
```

**Comment by christopherchoe** [comment]
Sorry about that! This application is super unfinished still, going to try and get it up an running in a couple weeks before I start work. Thanks for bringing it up!
